import { GoogleGenAI, Type } from "@google/genai";
import { CustomCakeDetails } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Parses a Google AI error and returns a user-friendly message.
 * @param error The error object from the API call.
 * @returns A string containing a user-friendly error message.
 */
const getFriendlyErrorMessage = (error: any): string => {
  const errorMessage = error.toString();
  console.error("Gemini API Error:", error);

  if (errorMessage.includes('[safety]')) {
    return "The description triggered our safety filters. Please try a more descriptive and appropriate prompt.";
  }
  if (errorMessage.includes('429')) { // Quota exceeded
    return "Our AI baker is very busy right now. Please try again in a few moments.";
  }
  if (errorMessage.includes('API_KEY_INVALID')) {
      return "There's an issue with our server configuration. Please contact support.";
  }
  
  return "Failed to generate cake details. Please try a different description.";
};


const cakeDetailsSchema = {
  type: Type.OBJECT,
  properties: {
    name: {
      type: Type.STRING,
      description: "A creative and appealing name for the cake, under 5 words."
    },
    description: {
      type: Type.STRING,
      description: "A short, tempting description of the cake, highlighting its key features and flavors. Max 30 words."
    },
    price: {
      type: Type.NUMBER,
      description: "An estimated price for the cake in South African Rand (R), considering its complexity, ingredients, and size. Should be a realistic bakery price."
    },
  },
  required: ["name", "description", "price"]
};

export const generateCakeDetails = async (prompt: string): Promise<CustomCakeDetails> => {
  const fullPrompt = `Based on the following user description, generate details for a custom cake. The pricing should be in South African Rand (R). User description: "${prompt}"`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: fullPrompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: cakeDetailsSchema,
      }
    });

    const jsonText = response.text.trim();
    const parsedJson = JSON.parse(jsonText);
    return parsedJson as CustomCakeDetails;
  } catch (error) {
    throw new Error(getFriendlyErrorMessage(error));
  }
};

export const generateCakeImage = async (prompt: string): Promise<string> => {
  const fullPrompt = `A high-quality, professional photograph of a custom cake. The cake is ${prompt}. It is beautifully decorated, looks delicious, and is the centerpiece on a clean, modern bakery display table. Photorealistic, soft lighting.`;
  
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: fullPrompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the AI.");
    }
  } catch (error) {
     throw new Error(getFriendlyErrorMessage(error));
  }
};